#!/bin/sh

# Directory containing this script
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_ROOT="$SCRIPT_DIR/../.."
VERSION_FILE="$PROJECT_ROOT/VERSION"
OUTPUT_FILE="$PROJECT_ROOT/src/platform/ios/WawonaIOSVersions.h"

# Read version from file
if [ -f "$VERSION_FILE" ]; then
    WAWONA_VERSION=$(cat "$VERSION_FILE" | tr -d '\n')
else
    WAWONA_VERSION="0.0.0-unknown"
fi

# Create directory if it doesn't exist
mkdir -p "$(dirname "$OUTPUT_FILE")"

# Write header file
cat > "$OUTPUT_FILE" <<EOF
// Generated by update_ios_versions.sh
// Do not edit manually

#ifndef WawonaIOSVersions_h
#define WawonaIOSVersions_h

#define WAWONA_VERSION_STRING "$WAWONA_VERSION"

// Dependency Versions (Static for now, ideally updated by Nix)
#define WAWONA_WAYLAND_VERSION "Bundled (Nix)"
#define WAWONA_WAYPIPE_VERSION "Bundled (Nix)"
#define WAWONA_MESA_VERSION "N/A"
#define WAWONA_EPOLL_SHIM_VERSION "Bundled"
#define WAWONA_LIBSSH2_VERSION "Bundled"
#define WAWONA_LIBFFI_VERSION "Bundled"
#define WAWONA_LZ4_VERSION "Bundled"
#define WAWONA_ZSTD_VERSION "Bundled"
#define WAWONA_XKBCOMMON_VERSION "Bundled"
#define WAWONA_SSHPASS_VERSION "Bundled"

#endif /* WawonaIOSVersions_h */
EOF

echo "Updated $OUTPUT_FILE with version $WAWONA_VERSION"
