// Generated by update_ios_versions.sh — fallback values only.
// When building via xcodegen, the canonical versions are injected
// through GCC_PREPROCESSOR_DEFINITIONS and take precedence.

#ifndef WWNIOSVersions_h
#define WWNIOSVersions_h

#ifndef WAWONA_VERSION
#define WAWONA_VERSION "0.2.1"
#endif

#ifndef WAWONA_VERSION_STRING
#define WAWONA_VERSION_STRING WAWONA_VERSION
#endif

// Dependency Versions — only defined if not already set by build system
#ifndef WAWONA_WAYLAND_VERSION
#define WAWONA_WAYLAND_VERSION "1.23.0"
#endif

#ifndef WAWONA_WAYPIPE_VERSION
#define WAWONA_WAYPIPE_VERSION "0.10.6"
#endif

#ifndef WAWONA_MESA_VERSION
#define WAWONA_MESA_VERSION "N/A"
#endif

#ifndef WAWONA_EPOLL_SHIM_VERSION
#define WAWONA_EPOLL_SHIM_VERSION "0.0.20240601"
#endif

#ifndef WAWONA_LIBSSH2_VERSION
#define WAWONA_LIBSSH2_VERSION "1.11.0"
#endif

#ifndef WAWONA_LIBFFI_VERSION
#define WAWONA_LIBFFI_VERSION "3.5.2"
#endif

#ifndef WAWONA_LZ4_VERSION
#define WAWONA_LZ4_VERSION "1.10.0"
#endif

#ifndef WAWONA_ZSTD_VERSION
#define WAWONA_ZSTD_VERSION "1.5.7"
#endif

#ifndef WAWONA_XKBCOMMON_VERSION
#define WAWONA_XKBCOMMON_VERSION "1.7.0"
#endif

#ifndef WAWONA_SSHPASS_VERSION
#define WAWONA_SSHPASS_VERSION "1.10"
#endif

#endif /* WWNIOSVersions_h */
